### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by 3052** [ferrellsl/VideoPlayer#1]
https://github.com/ferrellsl/VideoPlayer/releases

**Comment by 3052** [comment]
where is new release?

**Comment by ferrellsl** [comment]
Right where it's always been:  https://github.com/ferrellsl/VideoPlayer/releases

**Comment by 3052** [comment]
its old:
Nov 24, 2021

**Comment by ferrellsl** [comment]
FFS, that's the latest release.  If you don't like it, don't use it.  It works just fine under Windows 10 and 11.

**Comment by 3052** [comment]
ah I see, you haven't done anything since then:
https://github.com/ferrellsl/VideoPlayer/compare/2.1.1...main

have you considered just archiving the repo?

**Comment by ferrellsl** [comment]
Why should I archive it?  I intend to maintain this code so that I can fix bugs, if any are found.  To date, you're the only one complaining and you're only complaining because the code is 2+ years old which isn't a valid reason for archiving OR modifying this code.
